### PR TITLE
New options to check the attachments counts

### PR DESCRIPTION
**Pull request by gbeaudoin78**
Mostly useful to show attachments that are in the databse and missing from the filesystem. Which might be okay as far as the sync engine is concerned. I don't know if it's normal behavior or not.

That won't fix anything, it will just output some numbers.

### CODE REVIEW

**Comment by gbeaudoin78** [comment]
This will requires the following commands to be present on the system: find, uniq, wc, comm, egrep.

**Comment by snielson** [comment]
What if rather then adding a new menu option, this was added as part of the general health check?

**Comment by tdharris** [comment]
Looks like this could be helpful when troubleshooting attachment issues. Decided to merge this, looks great! Thanks!

**Comment by gbeaudoin78** [comment]
Yes, it could be added as part of the health check but it could be a little long to run.

**Comment by snielson** [comment]
I Agree. Best to keep this to its own option to select from the sub menus.

**Pull request merged**
